var GAME_LEVELS = [
 ["                                                                                    ",
  "                                                                                    ",
  "                                                                                    ",
  "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ", 
 "                                                                                    ",
 "                                    @                                               ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    ",
 "                                                                                    "]];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
